name: Android CI

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing ussd-library
        run: ./gradlew assembleDebug lint testDebugUnitTest -p ussd-library
      - name: Upload Testing ussd-library
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-test
          path: ussd-library/build/reports/tests/testDebugUnitTest
      - name: Upload ussd-library artifact
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-aar
          path: ussd-library/build/outputs/aar/ussd-library-debug.aar
      - name: Testing ussd-library-kotlin
        run: ./gradlew assembleDebug lint testDebugUnitTest -p ussd-library-kotlin
      - name: Upload Testing ussd-library-kotlin
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-kotlin-test
          path: ussd-library-kotlin/build/reports/tests/testDebugUnitTest
      - name: Upload ussd-library-kotlin artifact
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-kotlin-aar
          path: ussd-library-kotlin/build/outputs/aar/ussd-library-kotlin-debug.aar
